worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile    on;
    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 256;

    server {
        listen 80;
        server_name _;

        root /var/www/spa;
        index index.html;

        location ~ ^/api(/.*)?$ {
            set $api_path $1;
            if ($api_path = '') {
                set $api_path /;
            }

            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME /app/public/index.php;
            fastcgi_param REQUEST_URI $api_path$is_args$args;
            fastcgi_param DOCUMENT_ROOT /app/public;
            include fastcgi_params;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
